-file("/usr/local/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(aeva_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 84).

-export([is_keyword/1,is_type/1,is_funcscope/1]).

%% name_token(Chars, Line) ->
%%     {token,{'NAME',Line,Symbol}} | {Name,Line} | {error,E}.
%% Build a name from list of legal characters, else error.

name_token(Cs, L) ->
    case catch {ok,list_to_atom(Cs)} of
	{ok,Name} ->
	    case is_keyword(Name) of
		true -> {token,{Name,L}};
		false -> {token,{'NAME',L,Name}}
	    end;
	_ -> {error,"illegal name"}
    end.

%% base_token(Chars, Base, Line) -> Integer.
%% Convert a string of Base characters into a number. We know that
%% the strings only contain the correct character.

base_token(Cs, B, L) ->
    case base1(Cs, B, 0) of
	{I,[]} -> {token,{'NUMBER',L,I}};
	{_,_} -> {error,"illegal based number"}
    end.

base1([C|Cs], Base, SoFar) when C >= $0, C =< $9, C < Base + $0 ->
    Next = SoFar * Base + (C - $0),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $a, C =< $f, C < Base + $a - 10 ->
    Next = SoFar * Base + (C - $a + 10),
    base1(Cs, Base, Next);
base1([C|Cs], Base, SoFar) when C >= $A, C =< $F, C < Base + $A - 10 ->
    Next = SoFar * Base + (C - $A + 10),
    base1(Cs, Base, Next);
base1([C|Cs], _Base, SoFar) -> {SoFar,[C|Cs]};
base1([], _Base, N) -> {N,[]}.

%% string_token(InputChars, Length, Line) ->
%%      {token,{'STRING',Line,Cs}} | {error,E}.
%% Convert an input string into the corresponding string
%% characters. We know that the input string is correct.

string_token(Cs0, Len, L) ->
    Cs = string:substr(Cs0, 2, Len - 2),	%Strip quotes
    case catch {ok,chars(Cs)} of
	{ok,S} ->
	    {token,{'STRING',L,list_to_binary(S)}};
	error -> {error,"illegal string"}
    end.

chars([$\\,C1|Cs0]) when C1 >= $0, C1 =< $9 ->	%1-3 decimal digits
    I1 = C1 - $0,
    case Cs0 of
	[C2|Cs1] when C2 >= $0, C2 =< $9 ->
	    I2 = C2 - $0,
	    case Cs1 of
		[C3|Cs2] when C3 >= $0, C3 =< $9 ->
		    [100*I1 + 10*I2 + (C3-$0)|chars(Cs2)];
		_ -> [10*I1 + I2|chars(Cs1)]
	    end;
	_ -> [I1|chars(Cs0)]
    end;
chars([$\\,$x,C1,C2|Cs]) ->			%2 hex digits
    case hex_char(C1) and hex_char(C2) of
	true -> [hex_val(C1)*16+hex_val(C2)|chars(Cs)];
	false -> throw(error)
    end;
chars([$\\,$z|Cs]) -> chars(skip_space(Cs));	%Skip blanks
chars([$\\,C|Cs]) -> [escape_char(C)|chars(Cs)];
chars([$\n|_]) -> throw(error);
chars([C|Cs]) -> [C|chars(Cs)];
chars([]) -> [].

skip_space([C|Cs]) when C >= 0, C =< $\s -> skip_space(Cs);
skip_space(Cs) -> Cs.

hex_char(C) when C >= $0, C =< $9 -> true;
hex_char(C) when C >= $a, C =< $f -> true;
hex_char(C) when C >= $A, C =< $F -> true;
hex_char(_) -> false.

hex_val(C) when C >= $0, C =< $9 -> C - $0;
hex_val(C) when C >= $a, C =< $f -> C - $a + 10;
hex_val(C) when C >= $A, C =< $F -> C - $A + 10.

escape_char($n) -> $\n;				%\n = LF
escape_char($r) -> $\r;				%\r = CR
escape_char($t) -> $\t;				%\t = TAB
escape_char($v) -> $\v;				%\v = VT
escape_char($b) -> $\b;				%\b = BS
escape_char($f) -> $\f;				%\f = FF
escape_char($e) -> $\e;				%\e = ESC
escape_char($s) -> $\s;				%\s = SPC
escape_char($d) -> $\d;				%\d = DEL
escape_char(C) -> C.

%% is_keyword(Name) -> boolean().
%% Test if the name is a keyword.

is_keyword('and') -> true;
%%is_keyword('contract') -> true;
is_keyword('else') -> true;
is_keyword('elseif') -> true;
is_keyword('end') -> true;
is_keyword('false') -> true;
is_keyword('function') -> true;
is_keyword('if') -> true;
is_keyword('not') -> true;
is_keyword('null') -> true;
is_keyword('or') -> true;
%%is_keyword('private') -> true;
%%is_keyword('public') -> true;
is_keyword('return') -> true;
%%is_keyword('stateful') -> true;
is_keyword('then') -> true;
is_keyword('true') -> true;
is_keyword('var') -> true;
is_keyword(_) -> false.

%% is_type(Name) -> boolean().
%% Test if the name is a type.

is_type('address') -> true;
is_type('boolean') -> true;
is_type('integer') -> true;
is_type('string') -> true;
is_type('tokenaddress') -> true;
is_type('void') -> true;
is_type(_) -> false.

%% is_funcscope(Name) -> boolean().
%% Test if name is a function scope.

is_funcscope('private') -> true;
is_funcscope('public') -> true;
is_funcscope('stateful') -> true;
is_funcscope(_) -> false.

-file("/usr/local/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,Tlen,_Ics1,L1,_S1} ->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            string_cont(Tcs1, L2, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/4}).

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            token_cont(Tcs1, L2, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/3}).

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            tokens_cont(Tcs1, L2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/4}).

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/4}).

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.erl", 446).
yystate() -> 95.

yystate(98, [114|Ics], Line, Tlen, _, _) ->
    yystate(94, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(98, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,98};
yystate(97, [160|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 36, Tlen);
yystate(97, [32|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 36, Tlen);
yystate(97, [9|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line, Tlen+1, 36, Tlen);
yystate(97, [10|Ics], Line, Tlen, _, _) ->
    yystate(97, Ics, Line+1, Tlen+1, 36, Tlen);
yystate(97, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 13 ->
    yystate(97, Ics, Line, Tlen+1, 36, Tlen);
yystate(97, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,97};
yystate(96, [101|Ics], Line, Tlen, _, _) ->
    yystate(98, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(96, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,96};
yystate(95, [160|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(91, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(87, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(83, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [113|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [114|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [112|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [98|Ics], Line, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [95|Ics], Line, Tlen, Action, Alen) ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(29, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(49, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [32|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [9|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(97, Ics, Line+1, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 13 ->
    yystate(97, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 99, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 111 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, [C|Ics], Line, Tlen, Action, Alen) when C >= 119, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,95};
yystate(94, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(94, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 2, Tlen);
yystate(94, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,94};
yystate(93, Ics, Line, Tlen, _, _) ->
    {20,Tlen,Ics,Line};
yystate(92, [103|Ics], Line, Tlen, _, _) ->
    yystate(96, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(92, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,92};
yystate(91, Ics, Line, Tlen, _, _) ->
    {29,Tlen,Ics,Line};
yystate(90, [111|Ics], Line, Tlen, _, _) ->
    yystate(86, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(90, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,90};
yystate(89, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Tlen+1, Action, Alen);
yystate(89, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,89};
yystate(88, [101|Ics], Line, Tlen, _, _) ->
    yystate(92, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(88, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,88};
yystate(87, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(86, [111|Ics], Line, Tlen, _, _) ->
    yystate(82, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(86, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,86};
yystate(85, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line+1, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 91 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(85, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(85, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,85};
yystate(84, [116|Ics], Line, Tlen, _, _) ->
    yystate(88, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(84, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,84};
yystate(83, [111|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(83, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,83};
yystate(82, [108|Ics], Line, Tlen, _, _) ->
    yystate(78, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(82, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,82};
yystate(81, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(80, [110|Ics], Line, Tlen, _, _) ->
    yystate(84, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,80};
yystate(79, [105|Ics], Line, Tlen, _, _) ->
    yystate(75, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,79};
yystate(78, [101|Ics], Line, Tlen, _, _) ->
    yystate(74, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,78};
yystate(77, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(85, Ics, Line+1, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(85, Ics, Line, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,77};
yystate(76, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(76, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 6, Tlen);
yystate(76, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,76};
yystate(75, [100|Ics], Line, Tlen, _, _) ->
    yystate(71, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,75};
yystate(74, [97|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,74};
yystate(73, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(69, Ics, Line+1, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, [101|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(72, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,72};
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 5, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,71};
yystate(70, [110|Ics], Line, Tlen, _, _) ->
    yystate(66, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(70, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line};
yystate(68, [116|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(68, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,68};
yystate(67, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(67, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,67};
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,66};
yystate(65, [92|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(61, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line+1, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 40, C =< 91 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, [C|Ics], Line, Tlen, Action, Alen) when C >= 93 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(65, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,65};
yystate(64, [97|Ics], Line, Tlen, _, _) ->
    yystate(68, Ics, Line, Tlen+1, 9, Tlen);
yystate(64, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(64, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(64, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,64};
yystate(63, [111|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,63};
yystate(62, [100|Ics], Line, Tlen, _, _) ->
    yystate(58, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line};
yystate(60, [118|Ics], Line, Tlen, _, _) ->
    yystate(64, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 117 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, [C|Ics], Line, Tlen, _, _) when C >= 119, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,60};
yystate(59, [107|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 106 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, [C|Ics], Line, Tlen, _, _) when C >= 108, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(59, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,59};
yystate(58, [100|Ics], Line, Tlen, _, _) ->
    yystate(54, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,58};
yystate(57, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(65, Ics, Line+1, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(57, [C|Ics], Line, Tlen, Action, Alen) when C >= 11 ->
    yystate(65, Ics, Line, Tlen+1, Action, Alen);
yystate(57, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,57};
yystate(56, [105|Ics], Line, Tlen, _, _) ->
    yystate(60, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,56};
yystate(55, [101|Ics], Line, Tlen, _, _) ->
    yystate(51, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(55, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,55};
yystate(54, [114|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {26,Tlen,Ics,Line};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 7, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,52};
yystate(51, [110|Ics], Line, Tlen, _, _) ->
    yystate(47, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(51, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,51};
yystate(50, [101|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,50};
yystate(49, Ics, Line, Tlen, _, _) ->
    {27,Tlen,Ics,Line};
yystate(48, [99|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [97|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [98|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, [C|Ics], Line, Tlen, _, _) when C >= 100, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(48, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,48};
yystate(47, [97|Ics], Line, Tlen, _, _) ->
    yystate(43, Ics, Line, Tlen+1, 9, Tlen);
yystate(47, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(47, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(47, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,47};
yystate(46, [115|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(46, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,46};
yystate(45, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(44, [105|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,44};
yystate(43, [100|Ics], Line, Tlen, _, _) ->
    yystate(39, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,43};
yystate(42, [115|Ics], Line, Tlen, _, _) ->
    yystate(38, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,42};
yystate(41, Ics, Line, Tlen, _, _) ->
    {15,Tlen,Ics,Line};
yystate(40, [108|Ics], Line, Tlen, _, _) ->
    yystate(44, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(40, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,40};
yystate(39, [100|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(39, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,39};
yystate(38, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 0, Tlen);
yystate(38, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,38};
yystate(37, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(36, [98|Ics], Line, Tlen, _, _) ->
    yystate(40, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [97|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 99, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,36};
yystate(35, [114|Ics], Line, Tlen, _, _) ->
    yystate(31, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(33, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(32, [117|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [115|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [116|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [114|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(32, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,32};
yystate(31, [101|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,31};
yystate(30, Ics, Line, Tlen, _, _) ->
    {30,Tlen,Ics,Line};
yystate(29, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(28, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 8, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 8, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 8, Tlen);
yystate(28, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 8, Tlen);
yystate(28, Ics, Line, Tlen, _, _) ->
    {8,Tlen,Ics,Line,28};
yystate(27, [115|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,27};
yystate(26, [61|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 24, Tlen);
yystate(26, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,26};
yystate(25, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line};
yystate(24, [108|Ics], Line, Tlen, _, _) ->
    yystate(28, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 107 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 109, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,24};
yystate(23, [115|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(23, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,23};
yystate(22, Ics, Line, Tlen, _, _) ->
    {22,Tlen,Ics,Line};
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, 11, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Tlen+1, 11, Tlen);
yystate(21, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Tlen+1, 11, Tlen);
yystate(21, Ics, Line, Tlen, _, _) ->
    {11,Tlen,Ics,Line,21};
yystate(20, [117|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,20};
yystate(19, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 4, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,19};
yystate(18, [62|Ics], Line, Tlen, _, _) ->
    yystate(14, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, [61|Ics], Line, Tlen, _, _) ->
    yystate(10, Ics, Line, Tlen+1, 25, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line,18};
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 90 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(17, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 122 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,17};
yystate(16, [102|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 101 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, [C|Ics], Line, Tlen, _, _) when C >= 103, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(16, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,16};
yystate(15, [116|Ics], Line, Tlen, _, _) ->
    yystate(11, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,15};
yystate(14, Ics, Line, Tlen, _, _) ->
    {14,Tlen,Ics,Line};
yystate(13, [120|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 10, Tlen);
yystate(13, [88|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 10, Tlen);
yystate(13, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, 10, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,13};
yystate(12, [101|Ics], Line, Tlen, _, _) ->
    yystate(16, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(12, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,12};
yystate(11, [114|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [97|Ics], Line, Tlen, _, _) ->
    yystate(8, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 98, C =< 113 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {19,Tlen,Ics,Line};
yystate(9, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(9, Ics, Line, Tlen+1, 10, Tlen);
yystate(9, Ics, Line, Tlen, _, _) ->
    {10,Tlen,Ics,Line,9};
yystate(8, [116|Ics], Line, Tlen, _, _) ->
    yystate(12, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,8};
yystate(7, [105|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(7, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,7};
yystate(6, [61|Ics], Line, Tlen, _, _) ->
    yystate(2, Ics, Line, Tlen+1, 23, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {23,Tlen,Ics,Line,6};
yystate(5, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line};
yystate(4, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(4, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 3, Tlen);
yystate(4, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,4};
yystate(3, [110|Ics], Line, Tlen, _, _) ->
    yystate(0, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,3};
yystate(2, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(1, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(0, [103|Ics], Line, Tlen, _, _) ->
    yystate(4, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(67, Ics, Line, Tlen+1, 9, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {9,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, _, _, TokenLine) ->
    yyaction_0(TokenLine);
yyaction(1, _, _, TokenLine) ->
    yyaction_1(TokenLine);
yyaction(2, _, _, TokenLine) ->
    yyaction_2(TokenLine);
yyaction(3, _, _, TokenLine) ->
    yyaction_3(TokenLine);
yyaction(4, _, _, TokenLine) ->
    yyaction_4(TokenLine);
yyaction(5, _, _, TokenLine) ->
    yyaction_5(TokenLine);
yyaction(6, _, _, TokenLine) ->
    yyaction_6(TokenLine);
yyaction(7, _, _, TokenLine) ->
    yyaction_7(TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLen, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLen, TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, TokenLine) ->
    yyaction_35(TokenLine);
yyaction(36, _, _, _) ->
    yyaction_36();
yyaction(37, _, _, _) ->
    yyaction_37();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 19).
yyaction_0(TokenLine) ->
     { token, { type, TokenLine, address } } .

-compile({inline,yyaction_1/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 20).
yyaction_1(TokenLine) ->
     { token, { type, TokenLine, boolean } } .

-compile({inline,yyaction_2/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 21).
yyaction_2(TokenLine) ->
     { token, { type, TokenLine, integer } } .

-compile({inline,yyaction_3/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 22).
yyaction_3(TokenLine) ->
     { token, { type, TokenLine, string } } .

-compile({inline,yyaction_4/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 24).
yyaction_4(TokenLine) ->
     { token, { type, TokenLine, tokenaddress } } .

-compile({inline,yyaction_5/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 25).
yyaction_5(TokenLine) ->
     { token, { type, TokenLine, void } } .

-compile({inline,yyaction_6/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 28).
yyaction_6(TokenLine) ->
     { token, { funcscope, TokenLine, private } } .

-compile({inline,yyaction_7/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 29).
yyaction_7(TokenLine) ->
     { token, { funcscope, TokenLine, public } } .

-compile({inline,yyaction_8/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 30).
yyaction_8(TokenLine) ->
     { token, { funcscope, TokenLine, stateful } } .

-compile({inline,yyaction_9/2}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 34).
yyaction_9(TokenChars, TokenLine) ->
     name_token (TokenChars, TokenLine) .

-compile({inline,yyaction_10/2}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 38).
yyaction_10(TokenChars, TokenLine) ->
     case catch { ok, list_to_integer (TokenChars) } of
     { ok, I } -> { token, { 'NUMBER', TokenLine, I } } ;
     _ -> { error, "illegal number" }
     end .

-compile({inline,yyaction_11/2}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 43).
yyaction_11(TokenChars, TokenLine) ->
     base_token (string : substr (TokenChars, 3), 16, TokenLine) .

-compile({inline,yyaction_12/3}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 48).
yyaction_12(TokenChars, TokenLen, TokenLine) ->
     string_token (TokenChars, TokenLen, TokenLine) .

-compile({inline,yyaction_13/3}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 50).
yyaction_13(TokenChars, TokenLen, TokenLine) ->
     string_token (TokenChars, TokenLen, TokenLine) .

-compile({inline,yyaction_14/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 53).
yyaction_14(TokenLine) ->
     { token, { '=>', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 55).
yyaction_15(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 56).
yyaction_16(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 57).
yyaction_17(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 58).
yyaction_18(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 59).
yyaction_19(TokenLine) ->
     { token, { '==', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 60).
yyaction_20(TokenLine) ->
     { token, { '!=', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 61).
yyaction_21(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 62).
yyaction_22(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 63).
yyaction_23(TokenLine) ->
     { token, { '<', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 64).
yyaction_24(TokenLine) ->
     { token, { '>', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 65).
yyaction_25(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 66).
yyaction_26(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 67).
yyaction_27(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 68).
yyaction_28(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 69).
yyaction_29(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 70).
yyaction_30(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 71).
yyaction_31(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 72).
yyaction_32(TokenLine) ->
     { token, { ';', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 73).
yyaction_33(TokenLine) ->
     { token, { ':', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 74).
yyaction_34(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_35/1}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 75).
yyaction_35(TokenLine) ->
     { token, { '.', TokenLine } } .

-compile({inline,yyaction_36/0}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 77).
yyaction_36() ->
     skip_token .

-compile({inline,yyaction_37/0}).
-file("/Users/rv/aeternity/aeternity/apps/aevarna/src/aeva_scan.xrl", 80).
yyaction_37() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.1.6/include/leexinc.hrl", 313).
